
name: Launch EC2 with Monitoring Stack

on:
  workflow_dispatch:  # Manually trigger workflow

jobs:
  launch-instance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Launch EC2 Instance with User Data Script
        run: |
          aws ec2 run-instances \
            --image-id ami-084568db4383264d4 \
            --instance-type t3.micro \
            --key-name macbook \
            --security-groups default \
            --user-data file://user-data.sh \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=MonitoringInstance}]'
